"""added one more FK

Revision ID: 48d3d0763ac7
Revises: 3be7b1e060f9
Create Date: 2024-12-08 17:01:48.714279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48d3d0763ac7"
down_revision: Union[str, None] = "3be7b1e060f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("receiver_id", sa.Integer(), nullable=True))
    op.drop_index("ix_transaction_reciver_id", table_name="transaction")
    op.create_index(
        op.f("ix_transaction_receiver_id"), "transaction", ["receiver_id"], unique=False
    )
    op.drop_constraint("transaction_reciver_id_fkey", "transaction", type_="foreignkey")
    op.create_foreign_key(
        None, "transaction", "user", ["receiver_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("transaction", "reciver_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("reciver_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.create_foreign_key(
        "transaction_reciver_id_fkey",
        "transaction",
        "user",
        ["reciver_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_transaction_receiver_id"), table_name="transaction")
    op.create_index(
        "ix_transaction_reciver_id", "transaction", ["reciver_id"], unique=False
    )
    op.drop_column("transaction", "receiver_id")
    # ### end Alembic commands ###
