"""update statuses

Revision ID: 4b77072c4a39
Revises: 48d3d0763ac7
Create Date: 2024-12-08 20:18:15.217136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b77072c4a39"
down_revision: Union[str, None] = "48d3d0763ac7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transaction_receiver_id_fkey", "transaction", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "transaction_receiver_id_fkey",
        "transaction",
        "user",
        ["receiver_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
