"""change status type

Revision ID: 8b15251601ad
Revises: 150d03f98878
Create Date: 2024-12-08 22:42:11.388503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b15251601ad"
down_revision: Union[str, None] = "150d03f98878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "approved", "rejected", name="transactionstatus"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "pending", "approved", "rejected", name="transactionstatus"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
