FROM python:3.11.8-alpine3.19


RUN apk update && apk add --no-cache \
    gcc g++ musl-dev postgresql-dev libffi-dev build-base


WORKDIR /


COPY requirements.txt /


RUN pip install --no-cache-dir -r requirements.txt


COPY . /


WORKDIR /

EXPOSE 8002

CMD ["python", "transaction_service/main.py"]
