version: '3.9'

services:
  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.auth
    container_name: auth-service
    environment:
      - SERVICE_PORT=8001
      - ENVIRONMENT=local
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      - postgres

  transaction-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.transaction
    container_name: transaction-service
    environment:
      - SERVICE_PORT=8002
      - ENVIRONMENT=local
    ports:
      - "8002:8002"
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:12.16-alpine3.18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
    - AUTH_SERVICE_PORT=8001  
    - TRANSACTION_SERVICE_PORT=8002 
    depends_on:
      - auth-service
      - transaction-service
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
