FROM python:3.11.8-alpine3.19 AS transaction-service

WORKDIR /app

ENV PATH="/root/.local/bin:${PATH}"

COPY ./poetry.lock /app/
COPY ./pyproject.toml /app/

RUN pip install --no-cache-dir poetry


RUN poetry install --only transaction-service



CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
